### ISSUE TITLE
Prop `heading` doesn't render on chart.

### ISSUE THREAD

**Issue by will-lamerton** [Vue-Charts-CSS/vue.charts.css#2]
**Describe the bug**
When adding the prop `heading` and `show-heading` to the `charts-css` component, the passed heading is not rendered into the components `<caption/>` element despite `show-heading` DOM class being added correctly.

**Reduced test case**
```vue
<template>
     <charts-css
          type="bar"
          heading="Hello"
          show-heading
          :labels="['1', '2']"
          :datasets="[ { values: [4, 10] } ]"
          style="height: 5rem; max-width: 50%;"
     />
</template>
````

**Expected behaviour**
A heading should be visible in the DOM as per the documentation: https://vue-charts-css.github.io/docs/props/heading/

**Screenshots**
<img width="585" alt="Screenshot 2022-02-09 at 15 55 28" src="https://user-images.githubusercontent.com/89926355/153238532-1a1c7a58-ca68-4e97-bc2b-931438e5d108.png">
**Code used.**

<img width="1440" alt="Screenshot 2022-02-09 at 15 56 24" src="https://user-images.githubusercontent.com/89926355/153238714-86eaab59-102f-4a1a-ac63-fe272652a7fe.png">
**Output – as you can see, the `caption` is empty.**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: 1.34

**Comment by mrspence** [comment]
Is your `vue.charts.css` version `1.x.x`?

Unable to re-recreate your problem with `1.x.x` on [Code Sandbox](https://codesandbox.io/s/gallant-sea-q9rx7?file=/src/App.vue).

![image](https://user-images.githubusercontent.com/30320791/153268853-4fc1205f-7b3b-4c74-b058-425eca7d3494.png)

Suspect there's something else... if you have more information, please share 👍

**Comment by will-lamerton** [comment]
The issue appears here, obscure one to be fair: https://codesandbox.io/s/patient-rain-xv1m3?file=/src/App.vue

Dependencies are as follows and mimicked in the sandbox:
- vue: 2.6.12
- vue.charts.css: 1.0.2
- charts.css: 0.9.0

After playing around on sandbox, it appears it's an issue affecting Vue versions 2.6.12 and below. 2.6.13+ works as expected. 

<img width="1440" alt="Screenshot 2022-02-09 at 18 48 12" src="https://user-images.githubusercontent.com/89926355/153269323-973de9e2-79c7-40f8-8f9c-414025e5be45.png">
